### PR TITLE
jets: match hoon changes to bif:by

### PR DESCRIPTION
**Pull request by ashelkovnykov**
Companion PR to [#6639 in Arvo](https://github.com/urbit/urbit/pull/6639)

### CODE REVIEW

**Comment by ashelkovnykov** [comment]
Tests failing due to jet mismatch with the Hoon, just like in the companion PR

**Review by joemfb — COMMENTED** [review]
this pr needs to target `next/hoon/138`. changes look good.

**Review by joemfb — APPROVED** [review]
I didn't realize there was no `next/hoon/138` branch. created and retargeted.

this will do

**Comment by joemfb** [comment]
I was overeager with the merge button -- this interface change needs to be handled with different, kelvin-mediated old and new declarations in `tree.c`. I'll open another PR.

**Comment by ashelkovnykov** [comment]
@joemfb Right - let me know if you want me to do it instead, since I forgot that we need to support both the old and new jets for upgrade.

**Pull request merged**
