### PR TITLE
Add support for the %meme debug hint to the vere runtime

### LINKED ISSUE #166: Add the %meme hoon hint to the vere runtime
%meme is the last of the hints slated for work under my apprenticeship.
I have effectively completed this work, but am now migrating it to the vere repo.

For more information on my previous work please see https://github.com/urbit/urbit/pull/5967

### PR DESCRIPTION
**Pull request by DaneBettis**
### Description

Resolves #166 

I have added an support for the %meme hoon debugging hint. When a %meme hint is encountered, the usage of the vere memory arena is queried and printed (via slog).

The meme hint has two verbosity modes:
0: print the arena graph
1: print important memory information and the area graph

The arena graph is based on the ASCII graphs in Urbit's loom & road documentation

Example output in mode 0:
```
[=====$#############################################################################################~]
> ~>(%meme (add 1 1))
2
> =+  =+((bex (bex 30)) (bex (bex 30)))
  =+  =+((bex (bex 30)) (bex (bex 30)))
>>  warning: loom sums under 99.99%
>   after bexing: [=====$------------%%%%%%%%%%%%%%%%%%%%%%%%%########################################################~]
  ~>(%meme.[0 leaf+"after bexing"] (mul 100.000 100.003))
10.000.300.000
~zod:dojo> 
```
Example output in mode 1:
```
> =+  =+((bex (bex 30)) (bex (bex 30)))
  =+  =+((bex (bex 30)) (bex (bex 30)))
>>  warning: loom sums under 99.99%
>     after bexing
  Legend | Report:
                loom: 100.00%   2.147.482.236 GB     
                road:  93.25%   2.002.628.936 GB     

  =  immutable  heap:   6.45%     138.554.484 MB     
  -      solid  heap:  12.51%     268.661.488 MB     
  %      freed  heap:  25.00%     536.876.116 MB     
  #       open space:  55.74%   1.197.089.896 GB     
  +            stack:   0.00%           1.436 KB     
  ~  immutable stack:   0.29%       6.298.816 MB     

  $ allocation frame:   6.45%     138.554.484 MB     
      road direction:   South
          road depth:       4                        

Loom: [=====$------------%%%%%%%%%%%%%%%%%%%%%%%%%########################################################~]
  ~>(%meme.[1 leaf+"after bexing"] (mul 100.000 100.003))
10.000.300.000
~zod:dojo> 

```
if vere is compiled with the flag `CPU_DEBUG=1`, %meme mode 1 will report additional information:
```
> =+  =+((bex (bex 30)) (bex (bex 30)))
  =+  =+((bex (bex 30)) (bex (bex 30)))
>>  warning: loom sums under 99.99%
>     after bexing
  Legend | Report:
                loom: 100.00%   2.147.482.236 GB     
                road:  93.25%   2.002.628.952 GB     

  =  immutable  heap:   6.45%     138.554.468 MB     
  -      solid  heap:  12.51%     268.660.448 MB     
  %      freed  heap:  12.50%     268.440.916 MB     
  #       open space:  68.24%   1.465.526.152 GB     
  +            stack:   0.00%           1.436 KB     
  ~  immutable stack:   0.29%       6.298.816 MB     

  $ allocation frame:   6.45%     138.554.468 MB     
  |  road max memory:  25.50%     547.672.308 MB     

     road cells made:                  53.263 K      
     road nocks made:                  13.864 K      
      road direction:   South
          road depth:       4                        

Loom: [=====$-------------%%%%%|%%%%%%####################################################################~]
  ~>(%meme.[1 leaf+"after bexing"] (mul 100.000 100.003))
10.000.300.000
~zod:dojo> 
```

### Related
To see the basis of our ASCII graph design see, [this link](https://developers.urbit.org/reference/runtime/nouns) (scroll down to "u3: the road model"). There is similar info in `u3.md`.

This is the latest in a series of hoon debugging hints that I have authored: %bout, %hela, %nara, and %xray are my previous contributions.

### CODE REVIEW

**Comment by DaneBettis** [comment]
@mcevoypeter I have tested this locally and it looks good.
but it seems there is no automatic CI happening on github upon my pushing this PR in - should any CI be running?

**Comment by DaneBettis** [comment]
@mcevoypeter also, I'm trying to find how to pound-define a C macro at the command line in bazel.
In the old vere dev process, I just needed to use a related env var at the command line ahead of the configure/build command ```CPU_DEBUG=1 ./configure && make && build/urbit ../../../zod/```

and then the configure would call ```defmacro U3_CPU_DEBUG 1```

I've tried this in bazel, per the best docs/advice I could find online so far, but it doesn't seem to change the behavior governed by the macro being defined
```bazel build --define='U3_CPU_DEBUG=1' :urbit && ../urbit ../zod/``` 

any thoughts on this?

**Comment by mcevoypeter** [comment]
Sorry about the issues defining `U3_CPU_DEBUG`. https://github.com/urbit/vere/pull/142 hasn't been merged yet, and when it does, it should provide a template for how to do this sort of thing in the future. What are the compiler errors you're seeing? I cloned your fork, checked out `i/166/meme-hint`, and built using `bazel build --copt='-DU3_CPU_DEBUG=1' :urbit`, and it compiled without issue for me on `linux-x86_64`.

**Comment by mcevoypeter** [comment]
@joemfb can you give this another look? I know you reviewed it via https://github.com/urbit/urbit/pull/5967, and the comments seem to be all resolved. If there are no outstanding issues with it, we should merge it.

**Comment by DaneBettis** [comment]
@mcevoypeter I added includes into trace.h which resolved this by defining u3C.wag_w .

I also added a commit message for this

**Comment by DaneBettis** [comment]
@mcevoypeter As for docs; how about two places:
1. via doc-cords perhaps I can place it in repo urbit `./pkg/arvo/tests/run/hints.hoon` where my unit tests currently live
2. in the online docs ... perhaps somewhere under `https://developers.urbit.org/reference` within the hoon area?

I'm clearly open for input on this.

**Comment by mcevoypeter** [comment]
I'll defer to @joemfb's and your opinion for the comments so long as it's well-documented.

**Review by joemfb — COMMENTED** [review]
@DaneBettis thanks for your patience, and for restaging urbit/urbit#5967 here. The code looks good to me. I see some extra whitespace (two newlines) between most of these function definitions/declarations. Can you reduce that to one newline?

@mcevoypeter how can we get CI to run on this PR?

**Comment by mcevoypeter** [comment]
CI should request to run when @DaneBettis pushes another commit, at which point one of us can approve the run. The reason it hasn't run yet is because it looks like the last push came before I configured the GitHub Actions triggers correctly.

**Comment by joemfb** [comment]
@DaneBettis we'll also want the changes to the hoon unit tests from urbit/urbit#5967. You can reuse that PR, changing the base to `develop` and force-pushing over your branch.

**Comment by DaneBettis** [comment]
@joemfb @mcevoypeter I've pushed up another commit which addresses Joe's feedback. FYI.

**Comment by jalehman** [comment]
Re-requested your review @joemfb to get the formal stamp.

**Review by joemfb — APPROVED** [review]
Thanks, @DaneBettis!

this will do

**Pull request merged**
