### PR TITLE
Docker: Support for `--loom` and `--httpPort`

### LINKED ISSUE #189: Docker: support `--loom` and other options in start-urbit script
The start-urbit script is particular about what options it supports and does not pass through arbitrary options.  It does not support `--loom` and we can work around this for existing ships by calling `urbit` directly and not `start-urbit`.  There was a fix under review for this in the old repo but I never tried it out myself: 

https://github.com/urbit/urbit/pull/6110

Old issue: https://github.com/urbit/urbit/issues/6130

### PR DESCRIPTION
**Pull request by mopfel-winrux**
Modified start_urbit.sh script to allow the user to pick loom size and http port.
This is the start script Native Planet uses for our docker container

Resolves #189

### CODE REVIEW

**Comment by mcevoypeter** [comment]
If Native Planet is taking over ownership of the Docker container, I think it makes sense to change [CODEOWNERS](https://github.com/urbit/vere/tree/develop/.github/CODEOWNERS) to list your team as owners of the `docker/` directory. @jalehman thoughts?

**Comment by jalehman** [comment]
Agree completely. Let's make sure to due that durning one of our weekly meetings, probably tomorrow, @mopfel-winrux

**Comment by matthew-levan** [comment]
@mopfel-winrux will you please test this image and copy/paste the results in here? Maybe just a simple build, start (with new options), and verify that the boot prints match the expected inputs (namely `loom` size and `httpPort`).

**Review by matthew-levan — APPROVED** [review]
LGTM.

**Comment by matthew-levan** [comment]
@mopfel-winrux tested this live this morning and all the new options work as expected.

**Pull request merged**
