### PR TITLE
Shrink inter-road pad size to less than the size of an Urbit page

### LINKED ISSUE #292: Shrink inter-road pad size to less than the size of an Urbit page
2cacb2c49bbd44c82245c3910f6a78c9707ae183 introduced a fix (in the form of `u3e_ward()`) for the bug where the guard page resides within the pad between roads, allowing it to be "hopped" and rendered useless. A simpler alternative is to shrink the inter-road pad size to less than the size of an Urbit page, which means the pad will never be large enough to contain the entire guard page, thereby rendering it impossible for the guard page to be hopped.

### PR DESCRIPTION
**Pull request by mcevoypeter**
Resolves #292.

### CODE REVIEW

**Comment by joemfb** [comment]
This breaks the sampling profiler. And i'm not completely sure that it's the only thing depending on the pad.

**Comment by mcevoypeter** [comment]
Can you point me to the chunk(s) of code related to the sampling profiler that you know this breaks?

**Comment by joemfb** [comment]
Also, `u3e_ward()` isn't only intended to work around the existence of the pad. It *must* be called anytime the outside-in, page-at-a-time pattern of memory use (specifically *stores*) is not followed. Consider a large (multi-page) allocation on the stack of a north road, to be used in the typical pattern starting with the lowest address.

**Comment by joemfb** [comment]
See `u3t_samp()`.

**Comment by mcevoypeter** [comment]
>  u3e_ward() isn't only intended to work around the existence of the pad. It must be called anytime the outside-in, page-at-a-time pattern of memory use (specifically stores) is not followed.

Where else does this pattern of memory usage occur? Looking at call sites of `u3e_ward()`, I'm only seeing two, both in `u3m_leap()`, which suggests it's only being used as a work-around for the pad.

 > This breaks the sampling profiler.

I might be missing something, but I'm able to run the sampling profiler without apparent issue when using an 8KB pad.

**Comment by joemfb** [comment]
That pattern doesn't occur anywhere else at the moment. It would come up with moving more allocations to the stack (big buffers in jets, for instance) and/or optimizing the overflow checking within the allocator (which is currently redundant with the guard page in some situations).

If you have sufficient space in the free lists of parent-roads' heaps, the profiler won't have to use the pad. If the free lists are empty, or entries are too small, it will allocate on the hat, eating into the pad. 8KB is obviously not much space.

**Comment by mcevoypeter** [comment]
> That pattern doesn't occur anywhere else at the moment. It would come up with moving more allocations to the stack (big buffers in jets, for instance) and/or optimizing the overflow checking within the allocator (which is currently redundant with the guard page in some situations).

Got it. Thanks for explaining.

> If you have sufficient space in the free lists of parent-roads' heaps, the profiler won't have to use the pad. If the free lists are empty, or entries are too small, it will allocate on the hat, eating into the pad. 8KB is obviously not much space.

Is there any way to reliably produce the scenario where the profiler will allocate on the hat?

**Comment by mcevoypeter** [comment]
I ran the following on both the tip of this branch (a3ae06ba48c0ef230055f597f18231872ef196cb) and the tip of develop (fb7a8121468cf26365d8cb03db6de6dea2a10495):
```console
$ bazel build :urbit
$ ./urbit -j -F zod -u https://bootstrap.urbit.org/urbit-v1.22.pill
$ ./urbit -j zod
dojo> |pack
dojo> +solid
```
`+solid` command failed on a3ae06ba48c0ef230055f597f18231872ef196cb with:
```console
~zod:dojo> +solid %baseloom: not enough memory to recenter the guard page

recover: dig: meme
loom: not enough memory to recenter the guard page

recover: dig: meme
crud: %belt event failed
[%poke %belt]
wire=/use/dojo/0wHcgzE/~zod/~zod//hand/gen/solid
  bar-stack
[ i=[i=/dill t=[i=//term/1 t=~]]
    t
  [ i=[i=/gall/use/dojo/0wHcgzE/~zod/~zod//hand/gen/solid t=[i=/dill t=~[//term/1]]]
      t
    ~[
      [ i=/gall/use/hood/0wHcgzE/out/~zod/dojo/drum/phat/~zod/dojo
        t=[i=/dill t=~[//term/1]]
      ]
      [i=/dill/send/ t=[i=//term/1 t=~]]
      [i=//term/1 t=~]
    ]
  ]
]
take: failed
/sys/vane/gall/hoon:<[2.025 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.026 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.028 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.030 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.034 3].[2.041 5]>
[%gall-take-failed /use/dojo/0wHcgzE/~zod/~zod//hand/gen/solid]
/sys/vane/gall/hoon:<[2.035 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.036 3].[2.041 5]>
/sys/vane/gall/hoon:<[2.037 3].[2.041 5]>
/sys/vane/gall/hoon:<[589 5].[633 16]>
/sys/vane/gall/hoon:<[591 5].[633 16]>
/sys/vane/gall/hoon:<[595 5].[633 16]>
/sys/vane/gall/hoon:<[596 5].[633 16]>
/sys/vane/gall/hoon:<[597 5].[633 16]>
/sys/vane/gall/hoon:<[600 5].[633 16]>
/sys/vane/gall/hoon:<[604 5].[633 16]>
/sys/vane/gall/hoon:<[605 7].[614 18]>
/sys/vane/gall/hoon:<[608 7].[614 18]>
/sys/vane/gall/hoon:<[613 7].[614 18]>
/sys/vane/gall/hoon:<[613 16].[613 58]>
/sys/vane/gall/hoon:<[1.271 7].[1.277 14]>
/sys/vane/gall/hoon:<[1.272 7].[1.277 14]>
/sys/vane/gall/hoon:<[1.273 9].[1.274 47]>
/sys/vane/gall/hoon:<[1.593 7].[1.612 27]>
/sys/vane/gall/hoon:<[1.594 7].[1.612 27]>
/sys/vane/gall/hoon:<[1.594 19].[1.594 32]>
/sys/vane/gall/hoon:<[1.568 7].[1.574 9]>
/sys/vane/gall/hoon:<[1.569 7].[1.574 9]>
/sys/vane/gall/hoon:<[1.569 16].[1.569 51]>
http: fail (1, 504): I/O error (body; content-length)
docket: thread failed;
%retry-too-many
~
```

`+solid` failed on fb7a8121468cf26365d8cb03db6de6dea2a10495 with:
```console
~zod:dojo> +solid %baseloom: not enough memory to recenter the guard page

recover: dig: meme
address 0x39ba31b10 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in pkg/noun/events.c:272
Assertion failed: 0 (pkg/noun/events.c: u3e_fault: 272)
pier: serf unexpectedly shut down
```

@joemfb any idea what's going on here?

**Comment by joemfb** [comment]
You're running out of memory attempting to print the solid pill (a ~6MB atom). You can assign the result to a dojo variable to avoid printing it (`=foo +solid ...`, clear with `=foo`), or save it to the pier (as we usually do for export: `.solid/pill +solid ....` writes to `.urb/put/solid.pill`).

Also, `-j` is the *tracing* profiler, which writes JSON output to `.urb/put/trace/$N.json`. The *sampling* profiler is run with `-P`, and prints to the terminal on exit. (Also worth noting, `-P` output is much more useful with `U3_CPU_DEBUG`.)

**Comment by joemfb** [comment]
@mcevoypeter what's bailing? can you post the backtrace?

**Comment by mcevoypeter** [comment]
No backtrace is printed, and the bail is triggered by the first key press once the ship boots to dojo. Not sure if it's helpful, but here's `zod/.urb/put/trace/0.json` from running `./urbit -j -P zod` on the same pier: [0.json.log](https://github.com/urbit/vere/files/11030480/0.json.log)

**Comment by jalehman** [comment]
In light of [this comment](https://github.com/urbit/vere/pull/277#issuecomment-1478240930), closing this.

**Pull request closed without merging**
